// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit this file directly.
// Edit  data/retail_links.csv  then run:  npm run data:build
// ─────────────────────────────────────────────────────────────────────────────

export type Retailer = 'amazon' | 'tennisWarehouse' | 'tennisPoint' | 'other';
export type Region   = 'US' | 'UK' | 'EU' | 'GLOBAL';
export type ItemType = 'string' | 'racquet';
export type Currency = 'USD' | 'GBP' | 'EUR';

export type RetailLink = {
  itemType:       ItemType;
  itemSlug:       string;
  retailer:       Retailer;
  region:         Region;
  url:            string;    // affiliate URL; empty string for Amazon = auto-generated search URL
  isPrimary:      boolean;   // shown by default; false = shown after "Show more"
  price:          number | null;    // set manually from retailer; null = unknown
  currency:       Currency | null;  // required when price is set
  lastCheckedISO: string | null;    // ISO date string e.g. "2025-03-01"
};

export const retailLinks: RetailLink[] = [
  { itemType: 'string', itemSlug: 'luxilon-alu-power', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-alu-power', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/LUXILON_ALU_POWER.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-alu-power', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-alu-power', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/luxilon-alu-power?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-alu-power', retailer: 'amazon', region: 'EU', url: '', isPrimary: false, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-rpm-blast', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-rpm-blast', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/BABOLAT_RPM_BLAST.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-rpm-blast', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-rpm-blast', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/babolat-rpm-blast?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-tour-bite', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-tour-bite', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/SOLINCO_TOUR_BITE.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-tour-bite', retailer: 'amazon', region: 'UK', url: '', isPrimary: false, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-hyper-g', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-hyper-g', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/SOLINCO_HYPER_G.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'head-hawk', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'head-hawk', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/HEAD_HAWK.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'head-hawk', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/head-hawk?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'head-hawk', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-black-code', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-black-code', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/TECNIFIBRE_BLACK_CODE.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-black-code', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/tecnifibre-black-code?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-nxt', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-nxt', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/WILSON_NXT.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-nxt', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-nxt', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/wilson-nxt?ref=AFFILIATE_TAG', isPrimary: false, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-x-one-biphase', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-x-one-biphase', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/TECNIFIBRE_X1_BIPHASE.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'tecnifibre-x-one-biphase', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/tecnifibre-x-one-biphase?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-vs-team', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-vs-team', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/BABOLAT_VS_TEAM.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'babolat-vs-team', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/babolat-vs-team?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-natural-gut', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'wilson-natural-gut', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/WILSON_NATURAL_GUT.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'prince-synthetic-gut', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'prince-synthetic-gut', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'yonex-poly-tour-pro', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'yonex-poly-tour-pro', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/YONEX_POLY_TOUR_PRO.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'yonex-poly-tour-pro', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/yonex-poly-tour-pro?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-4g', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-4g', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/LUXILON_4G.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-4g', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/luxilon-4g?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-4g-rough', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'luxilon-4g-rough', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/LUXILON_4G_ROUGH.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-confidential', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'string', itemSlug: 'solinco-confidential', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/SOLINCO_CONFIDENTIAL.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-pro-staff-97-v14', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-pro-staff-97-v14', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/WILSON_PRO_STAFF_97.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-pro-staff-97-v14', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-pro-staff-97-v14', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/wilson-pro-staff-97?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'babolat-pure-aero-2023', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'babolat-pure-aero-2023', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/BABOLAT_PURE_AERO_2023.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'babolat-pure-aero-2023', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'babolat-pure-aero-2023', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/babolat-pure-aero-2023?ref=AFFILIATE_TAG', isPrimary: false, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'head-speed-mp-2024', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'head-speed-mp-2024', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/HEAD_SPEED_MP_2024.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'head-speed-mp-2024', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/head-speed-mp-2024?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-blade-98-16x19-v9', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-blade-98-16x19-v9', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/WILSON_BLADE_98.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'wilson-blade-98-16x19-v9', retailer: 'amazon', region: 'UK', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'yonex-ezone-98-2024', retailer: 'amazon', region: 'US', url: '', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'yonex-ezone-98-2024', retailer: 'tennisWarehouse', region: 'US', url: 'https://www.tenniswarehouse.com/p/YONEX_EZONE_98_2024.html?src=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null },
  { itemType: 'racquet', itemSlug: 'yonex-ezone-98-2024', retailer: 'tennisPoint', region: 'EU', url: 'https://www.tennis-point.com/yonex-ezone-98-2024?ref=AFFILIATE_TAG', isPrimary: true, price: null, currency: null, lastCheckedISO: null }
];
