/**
 * scripts/build-data.ts
 *
 * Reads data/strings.csv, data/racquets.csv, and data/retail_links.csv,
 * validates the data, then writes generated TypeScript files to:
 *   data/strings.ts
 *   data/racquets.ts
 *   data/retailLinks.ts
 *
 * Run with: npm run data:build
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const DATA = join(ROOT, 'data');

// ─── Colour helpers (no dependencies) ────────────────────────────────────────
const c = {
  red:    (s: string) => `\x1b[31m${s}\x1b[0m`,
  green:  (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  bold:   (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim:    (s: string) => `\x1b[2m${s}\x1b[0m`,
};

// ─── CSV parser (RFC 4180, quoted fields, embedded commas) ───────────────────
function parseCSV(raw: string): Record<string, string>[] {
  const normalised = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const lines = normalised.split('\n').filter(l => l.trim() && !l.trim().startsWith('#'));
  if (lines.length < 2) return [];
  const headers = parseCSVRow(lines[0]);
  return lines.slice(1).map(line => {
    const vals = parseCSVRow(line);
    const row: Record<string, string> = {};
    headers.forEach((h, i) => (row[h.trim()] = (vals[i] ?? '').trim()));
    return row;
  });
}

function parseCSVRow(line: string): string[] {
  const fields: string[] = [];
  let cur = '';
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQ && line[i + 1] === '"') { cur += '"'; i++; }
      else inQ = !inQ;
    } else if (ch === ',' && !inQ) {
      fields.push(cur); cur = '';
    } else {
      cur += ch;
    }
  }
  fields.push(cur);
  return fields;
}

// ─── Validation helpers ───────────────────────────────────────────────────────
interface VError { row: number; field: string; message: string }

function require(
  row: Record<string, string>, field: string,
  rowNum: number, errs: VError[],
) {
  if (!row[field]?.trim())
    errs.push({ row: rowNum, field, message: `Required field "${field}" is empty` });
}

function requireNum(
  row: Record<string, string>, field: string,
  rowNum: number, errs: VError[],
) {
  const v = row[field]?.trim();
  if (v === undefined || v === '') return; // optional – skip
  if (isNaN(Number(v)))
    errs.push({ row: rowNum, field, message: `"${field}" must be a number, got "${v}"` });
}

function requireOneOf(
  row: Record<string, string>, field: string, allowed: Set<string>,
  rowNum: number, errs: VError[],
) {
  const v = row[field]?.trim();
  if (v && !allowed.has(v))
    errs.push({ row: rowNum, field, message: `"${field}" must be one of [${[...allowed].join(', ')}], got "${v}"` });
}

function bail(errs: VError[], label: string): void {
  console.error(c.red(`\n✖  Validation failed — ${label}:`));
  errs.forEach(e =>
    console.error(`   Row ${e.row}  [${e.field}]: ${e.message}`)
  );
  process.exit(1);
}

// ─── TypeScript generation helpers ───────────────────────────────────────────
function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ');
}
function str(s: string) { return `'${esc(s)}'`; }
function arr(items: string[]) { return `[${items.map(str).join(', ')}]`; }
function num(s: string, fallback = 0) { return isNaN(Number(s)) ? fallback : Number(s); }
function bool(s: string) { return s.trim().toLowerCase() === 'true'; }
function pipe(s: string) { return s.split('|').map(x => x.trim()).filter(Boolean); }

/** Convert balance cm to categorical Balance type. */
function balanceCmToBalance(cm: number): 'HL' | 'Even' | 'HH' {
  if (cm < 32.5) return 'HL';
  if (cm < 34.5) return 'Even';
  return 'HH';
}

const GENERATED_BANNER = (csv: string) =>
  `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit this file directly.
// Edit  data/${csv}  then run:  npm run data:build
// ─────────────────────────────────────────────────────────────────────────────
`;

// ─── STRINGS ─────────────────────────────────────────────────────────────────
const STRING_TYPES  = new Set(['polyester', 'multifilament', 'natural-gut', 'synthetic-gut']);
const STRING_FEELS  = new Set(['crisp', 'soft', 'firm', 'lively']);
const STRING_SHAPES = new Set(['round', 'pentagonal', 'hexagonal', 'octagonal', 'textured']);
const PRICE_BANDS   = new Set(['budget', 'mid', 'premium']);

function buildStrings(csvPath: string): { slugs: Set<string>; output: string } {
  const raw = readFileSync(csvPath, 'utf8');
  const rows = parseCSV(raw);
  const errs: VError[] = [];
  const slugs = new Set<string>();

  const REQ_FIELDS = [
    'slug', 'brand', 'name', 'type', 'feel', 'shape',
    'gauges', 'armFriendly', 'priceBand',
    'spin', 'control', 'power', 'comfort', 'durability', 'notes',
  ];
  const NUM_FIELDS = ['spin', 'control', 'power', 'comfort', 'durability'];

  rows.forEach((row, i) => {
    const rowNum = i + 2;
    REQ_FIELDS.forEach(f => require(row, f, rowNum, errs));
    NUM_FIELDS.forEach(f => requireNum(row, f, rowNum, errs));
    requireOneOf(row, 'type',      STRING_TYPES,  rowNum, errs);
    requireOneOf(row, 'feel',      STRING_FEELS,  rowNum, errs);
    requireOneOf(row, 'shape',     STRING_SHAPES, rowNum, errs);
    requireOneOf(row, 'priceBand', PRICE_BANDS,   rowNum, errs);
    const slug = row.slug?.trim();
    if (slug) {
      if (slugs.has(slug)) errs.push({ row: rowNum, field: 'slug', message: `Duplicate slug "${slug}"` });
      else slugs.add(slug);
    }
  });

  if (errs.length) bail(errs, 'strings.csv');

  const items = rows.map((row, i) => {
    const gauges  = pipe(row.gauges);
    const whyPick = pipe(row.whyPick ?? '');
    return `  {
    id: ${str(String(i + 1))},
    slug: ${str(row.slug)},
    name: ${str(row.name)},
    brand: ${str(row.brand)},
    type: ${str(row.type)},
    feel: ${str(row.feel)},
    shape: ${str(row.shape)},
    gauges: ${arr(gauges)},
    armFriendly: ${bool(row.armFriendly)},
    priceBand: ${str(row.priceBand)},
    ratings: { spin: ${num(row.spin)}, power: ${num(row.power)}, control: ${num(row.control)}, comfort: ${num(row.comfort)}, durability: ${num(row.durability)} },
    description: ${str(row.notes)},
    whyPick: ${arr(whyPick)},
  }`;
  });

  const output = `${GENERATED_BANNER('strings.csv')}
import type { TennisString } from '@/types';

export const strings: TennisString[] = [
${items.join(',\n')}
];

export function getStringBySlug(slug: string): TennisString | undefined {
  return strings.find((s) => s.slug === slug);
}

export function getStringsBySlugs(slugs: string[]): TennisString[] {
  return slugs.map((slug) => strings.find((s) => s.slug === slug)).filter(Boolean) as TennisString[];
}
`;

  return { slugs, output };
}

// ─── RACQUETS ─────────────────────────────────────────────────────────────────
const LEVELS = new Set(['beginner', 'intermediate', 'advanced', 'pro']);

function buildRacquets(
  csvPath: string,
  validStringSlugs: Set<string>,
): { slugs: Set<string>; output: string } {
  const raw = readFileSync(csvPath, 'utf8');
  const rows = parseCSV(raw);
  const errs: VError[] = [];
  const slugs = new Set<string>();

  const REQ_FIELDS = [
    'slug', 'brand', 'model', 'level', 'pattern',
    'headSizeSqIn', 'weightStrungG', 'balanceStrungCm',
    'stringTensionMinLbs', 'stringTensionMaxLbs', 'notes',
  ];
  const NUM_FIELDS = [
    'headSizeSqIn', 'weightStrungG', 'balanceStrungCm',
    'stringTensionMinLbs', 'stringTensionMaxLbs',
  ];

  rows.forEach((row, i) => {
    const rowNum = i + 2;
    REQ_FIELDS.forEach(f => require(row, f, rowNum, errs));
    NUM_FIELDS.forEach(f => requireNum(row, f, rowNum, errs));
    requireNum(row, 'stiffnessRA', rowNum, errs); // optional numeric
    requireOneOf(row, 'level', LEVELS, rowNum, errs);

    const slug = row.slug?.trim();
    if (slug) {
      if (slugs.has(slug)) errs.push({ row: rowNum, field: 'slug', message: `Duplicate slug "${slug}"` });
      else slugs.add(slug);
    }

    // Validate recommendedStrings references
    if (row.recommendedStrings?.trim()) {
      pipe(row.recommendedStrings).forEach(s => {
        if (!validStringSlugs.has(s))
          errs.push({ row: rowNum, field: 'recommendedStrings', message: `Unknown string slug "${s}"` });
      });
    }
  });

  if (errs.length) bail(errs, 'racquets.csv');

  const items = rows.map((row, i) => {
    const balanceCm  = num(row.balanceStrungCm);
    const balance    = balanceCmToBalance(balanceCm);
    const recStrings = pipe(row.recommendedStrings ?? '');
    const stiffRA    = row.stiffnessRA?.trim() ? `\n    stiffnessRA: ${num(row.stiffnessRA)},` : '';
    const recLine    = recStrings.length
      ? `\n    recommendedStrings: ${arr(recStrings)},`
      : '';

    return `  {
    id: ${str(String(i + 1))},
    slug: ${str(row.slug)},
    name: ${str(row.model)},
    brand: ${str(row.brand)},
    headSize: ${num(row.headSizeSqIn)},
    weight: ${num(row.weightStrungG)},
    balance: ${str(balance)},${stiffRA}
    stringPattern: ${str(row.pattern)},
    tensionMin: ${num(row.stringTensionMinLbs)},
    tensionMax: ${num(row.stringTensionMaxLbs)},
    level: ${str(row.level)},
    description: ${str(row.notes)},${recLine}
  }`;
  });

  const output = `${GENERATED_BANNER('racquets.csv')}
import type { Racquet } from '@/types';

export const racquets: Racquet[] = [
${items.join(',\n')}
];

export function getRacquetBySlug(slug: string): Racquet | undefined {
  return racquets.find((r) => r.slug === slug);
}
`;

  return { slugs, output };
}

// ─── RETAIL LINKS ─────────────────────────────────────────────────────────────
const RETAILERS  = new Set(['amazon', 'tennisWarehouse', 'tennisPoint', 'other']);
const REGIONS    = new Set(['US', 'UK', 'EU', 'GLOBAL']);
const ITEM_TYPES = new Set(['string', 'racquet']);
const CURRENCIES = new Set(['USD', 'GBP', 'EUR']);

function buildRetailLinks(
  csvPath: string,
  validStringSlugs: Set<string>,
  validRacquetSlugs: Set<string>,
): string {
  const raw = readFileSync(csvPath, 'utf8');
  const rows = parseCSV(raw);
  const errs: VError[] = [];

  rows.forEach((row, i) => {
    const rowNum = i + 2;
    // url is optional for amazon (auto-generated from item name at runtime)
    const baseFields = ['itemType', 'itemSlug', 'retailer', 'region', 'isPrimary'];
    baseFields.forEach(f => require(row, f, rowNum, errs));
    if (row.retailer?.trim() !== 'amazon') require(row, 'url', rowNum, errs);
    requireOneOf(row, 'itemType', ITEM_TYPES, rowNum, errs);
    requireOneOf(row, 'retailer', RETAILERS,  rowNum, errs);
    requireOneOf(row, 'region',   REGIONS,    rowNum, errs);
    requireNum(row, 'price', rowNum, errs); // optional numeric

    if (row.currency?.trim() && !CURRENCIES.has(row.currency.trim()))
      errs.push({ row: rowNum, field: 'currency', message: `"currency" must be USD, GBP, or EUR` });

    const priceSet = row.price?.trim();
    const currSet  = row.currency?.trim();
    if (priceSet && !currSet)
      errs.push({ row: rowNum, field: 'currency', message: `"currency" is required when "price" is set` });

    const slug = row.itemSlug?.trim();
    if (slug && row.itemType) {
      const valid =
        row.itemType === 'string'  ? validStringSlugs.has(slug)  :
        row.itemType === 'racquet' ? validRacquetSlugs.has(slug) :
        false;
      if (!valid)
        errs.push({ row: rowNum, field: 'itemSlug', message: `No ${row.itemType} with slug "${slug}"` });
    }
  });

  if (errs.length) bail(errs, 'retail_links.csv');

  const items = rows.map(row => {
    const priceVal   = row.price?.trim()          ? num(row.price)                : 'null';
    const currVal    = row.currency?.trim()        ? str(row.currency.trim())      : 'null';
    const checkedVal = row.lastCheckedISO?.trim()  ? str(row.lastCheckedISO.trim()) : 'null';
    return `  { itemType: ${str(row.itemType)}, itemSlug: ${str(row.itemSlug)}, retailer: ${str(row.retailer)}, region: ${str(row.region)}, url: ${str(row.url)}, isPrimary: ${bool(row.isPrimary)}, price: ${priceVal}, currency: ${currVal}, lastCheckedISO: ${checkedVal} }`;
  });

  return `${GENERATED_BANNER('retail_links.csv')}
export type Retailer = 'amazon' | 'tennisWarehouse' | 'tennisPoint' | 'other';
export type Region   = 'US' | 'UK' | 'EU' | 'GLOBAL';
export type ItemType = 'string' | 'racquet';
export type Currency = 'USD' | 'GBP' | 'EUR';

export type RetailLink = {
  itemType:       ItemType;
  itemSlug:       string;
  retailer:       Retailer;
  region:         Region;
  url:            string;    // affiliate URL; empty string for Amazon = auto-generated search URL
  isPrimary:      boolean;   // shown by default; false = shown after "Show more"
  price:          number | null;    // set manually from retailer; null = unknown
  currency:       Currency | null;  // required when price is set
  lastCheckedISO: string | null;    // ISO date string e.g. "2025-03-01"
};

export const retailLinks: RetailLink[] = [
${items.join(',\n')}
];
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
function main() {
  console.log(c.bold('\n🎾  StringLab data build\n'));

  // 1. Strings
  process.stdout.write('  Strings   ');
  const { slugs: stringSlugs, output: stringsTS } =
    buildStrings(join(DATA, 'strings.csv'));
  writeFileSync(join(DATA, 'strings.ts'), stringsTS, 'utf8');
  console.log(c.green(`✔  ${stringSlugs.size} strings → data/strings.ts`));

  // 2. Racquets
  process.stdout.write('  Racquets  ');
  const { slugs: racquetSlugs, output: racquetsTS } =
    buildRacquets(join(DATA, 'racquets.csv'), stringSlugs);
  writeFileSync(join(DATA, 'racquets.ts'), racquetsTS, 'utf8');
  console.log(c.green(`✔  ${racquetSlugs.size} racquets → data/racquets.ts`));

  // 3. Retail links
  process.stdout.write('  Links     ');
  const linksTS = buildRetailLinks(
    join(DATA, 'retail_links.csv'),
    stringSlugs,
    racquetSlugs,
  );
  writeFileSync(join(DATA, 'retailLinks.ts'), linksTS, 'utf8');
  const linkCount = parseCSV(readFileSync(join(DATA, 'retail_links.csv'), 'utf8')).length;
  console.log(c.green(`✔  ${linkCount} links → data/retailLinks.ts`));

  console.log(c.bold(c.green('\n  Done. Run `npm run build` to verify.\n')));
}

main();
